# Generated by Django 5.1.2 on 2024-12-16 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="featured_image",
            new_name="thumbnail",
        ),
    ]
