# Generated by Django 5.1.2 on 2025-01-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_expertise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("file", models.FileField(upload_to="gallery/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
