# Generated by Django 5.1.2 on 2025-01-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="title",
            field=models.CharField(default="random", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gallery",
            name="tag",
            field=models.CharField(
                choices=[
                    ("Event A", "Event A"),
                    ("Event B", "Event B"),
                    ("Event C", "Event C"),
                ],
                max_length=50,
            ),
        ),
    ]
